### ISSUE TITLE
sem_timedwait is not available on macOS and BSD-based systems.

### ISSUE THREAD

**Issue by hjstn** [WatchBeam/ftl-sdk#28]
In the version of ftl-sdk that's compiled as a plugin in obs-studio-ftl, obs-studio-ftl/plugins/libftl/ftl-sdk/libftl/ftl_helpers.c (ln252), sem_timedwait, a function unavailabe in BSD-based systems is used. This prevents a successful compilation of ftl-sdk on BSD-based systems.

**Comment by sslivins** [comment]
thanks @justin97530 i'll take a look

**Comment by sslivins** [comment]
this has been resolved
