### ISSUE TITLE
No instructions on how to build for iOS

### ISSUE THREAD

**Issue by outcast** [WatchBeam/ftl-sdk#39]
The instruction provide do not clear state how to build for iOS. Have tried what is documented but always ends in error. I am build on OSX  10.11.6 using XCode 8.1. Using non-brew managed cmake.

**Comment by QuinnDamerell-MS** [comment]
Can you try updating ftl, the submodules, and cmake and see if this is still happening? If so please post the error. :)

**Comment by QuinnDamerell-MS** [comment]
Please reopen if you're still having trouble.
